# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  workflow_dispatch:
    inputs:
      module :
        type: choice
        description: 'Run workflow'
        options :
         - 'Build'
        required: true
      from_date:
        type: string
        description: 'Enter From Date'
      to_date:
        type: string
        description: 'Enter To Date'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build & run
      run: |
        python main.py
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
            name: weekly_report
            path: ${{ github.workspace }}/*.csv
            retention-days: 7
    - name: Update yaml file
      run: |
        sed -i 's/fromdate: [^ ]*/tag: "${{inputs.from_date}}"/g' ${{github.workspace}}/config/values.yaml
        sed -i 's/todate: [^ ]*/tag: "${{inputs.from_date}}"/g' ${{github.workspace}}/config/values.yaml
        cat ${{github.workspace}}/config/values.yaml
      
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with: 
            name: weekly_report
