# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  schedule:
    - cron: "0 23 * * *"

  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
    Daily_Update:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3

        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: "3.10"

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        - name: Build & run
          run: |
            python main.py

        - run : |
            ls
            pwd

        - name : Upload Artifact
          uses: actions/upload-artifact@v3
          with:
            name: my-artifact
            path: ${{ github.workspace }}/prices_report.csv
        
        - name : Download Artifact
          uses: actions/download-artifact@v3
          with: 
            name: my-artifact

        

